use_nerdfont = true
audio_cache_size = 200
shuffle = true

[theme]
background = "#FFFFFF"
primary = "#373737"
secondary = "#C6C6C6"
title = "#373737"
playing = "#009435"
playing_selected = "#005F22"
playing_bg = "#F5F5F5"
highlight = "#515151"
highlight_bg = "#C0C0C0"
error = "#FF7373"
error_bg = "#A00000"
statusbar = "#272727"
statusbar_progress = "#009A44"
statusbar_bg = "#00AC4C"
cmdline = "#000000"
cmdline_bg = "#FFFFFF"

