theme = "gruber-darker"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
