name: Dry Run

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest

    env:
      DRY_RUN: true

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Grant permissions
      run: chmod +x setup.sh

    - name: Run script
      run: ./setup.sh